###Numpy Array Operations

In [2]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
#arr=np.arange(1,11)
print("Basic slicing:",arr[2:9])
print("With step:",arr[1:6:2])
print("Negative Slicing:",arr[-5])

Basic slicing: [3 4 5 6 7 8 9]
With step: [2 4 6]
Negative Slicing: 6


### Operations on 2D array

In [9]:
                # 0 1 2   
arr_2d=np.array([[1,2,3],  #0
                 [4,5,6],  #1
                 [7,8,9]]) #2

print("Single Element:",arr_2d[0,1])
# print("Single Element:",arr_2d[row,column])
print("Entire row:",arr_2d[2])
print("Entire column:",arr_2d[:,1])

Single Element: 2
Entire row: [7 8 9]
Entire column: [2 5 8]


### Sorting

In [16]:
unsorted=np.array([2,3,21,4,3,3,1])
print("Sorting 1D array:",np.sort(unsorted))

unsorted_2d=np.array([[8,1,3,4],
                      [6,1,3,1],
                      [1,4,2,9]])
print("Sorting 2D array by column:\n",np.sort(unsorted_2d,axis=0))
print("Sorting 2D array by row:\n",np.sort(unsorted_2d,axis=1))

Sorting 1D array: [ 1  2  3  3  3  4 21]
Sorting 2D array by column:
 [[1 1 2 1]
 [6 1 3 4]
 [8 4 3 9]]
Sorting 2D array by row:
 [[1 3 4 8]
 [1 1 3 6]
 [1 2 4 9]]


### Filtering

In [4]:
numbers=np.array([1,2,34,2,2,5,14,13])
even_numbers=numbers[numbers%2==0]
print("Even Numbers:",even_numbers)

Even Numbers: [ 2 34  2  2 14]


### Filtering with Mask

In [18]:
mask=numbers>15
print("Numbers greater than 15:",numbers[mask])

Numbers greater than 15: [34]


### Fancy Indexing v/s np.where()

In [8]:
indices=[0,2,4]
print(numbers[indices])

where_result=np.where(numbers>5)
print("Using where():",numbers[where_result])

[ 1 34  2]
Using where(): [34 14 13]


In [10]:
condition_array=np.where(numbers>5,numbers*2,numbers)
print(condition_array)

true_false=np.where(numbers>5,"True","False")
print(true_false)

[ 1  2 68  2  2  5 28 26]
['False' 'False' 'True' 'False' 'False' 'False' 'True' 'True']


Conditional array in if else

if(numbers>5){
    numbers*2
}else{
    numbers
}

### Adding And Removing Data

In [11]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6]) 

combined=np.concatenate((arr1,arr2))
print("Combined :",combined)

Combined : [1 2 3 4 5 6]


### Array Compatibility

In [13]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9,10])

print("Compatibility of a and b:",a.shape==b.shape)
print("Compatibility of c and b:",c.shape==b.shape)

Compatibility of a and b: True
Compatibility of c and b: False


In [18]:
original = np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])
               #vertical stack
with_new_row=np.vstack((original,new_row))
print("Original:\n",original)
print("Added row:\n",with_new_row)

new_col=np.array([[5],[6]])
with_new_col=np.hstack((original,new_col))
print("Added column:\n",with_new_col)

Original:
 [[1 2]
 [3 4]]
Added row:
 [[1 2]
 [3 4]
 [5 6]]
Added column:
 [[1 2 5]
 [3 4 6]]


In [19]:
array=np.array([1,2,3,4,5])
deleted=np.delete(array,3)
print("Original:\n",array)
print("Deleted array:\n",deleted)

Original:
 [1 2 3 4 5]
Deleted array:
 [1 2 3 5]
