In [2]:
import numpy as np

#Creating array from list

In [3]:
arr_1d=np.array([1,2,3,4,5,6])
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_1d)
print(arr_2d)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


#List vs Numpy Array

In [9]:
py_list=[1,2,3]
print("Python list:",py_list * 2)

ny_array=np.array([1,2,3])
print("Numpy array:",ny_array * 2)

import time

start=time.time()
py_list=[i*2 for i in range(1000000)]
print("Time taken for python list:",time.time()-start)

start2=time.time()
ny_array=np.arange(1000000)*2
print("Time taken for numpy array:",time.time()-start2)

Python list: [1, 2, 3, 1, 2, 3]
Numpy array: [2 4 6]
Time taken for python list: 0.10519576072692871
Time taken for numpy array: 0.006287813186645508
