In [2]:
import numpy as np

#Creating array from list

In [3]:
arr_1d=np.array([1,2,3,4,5,6])
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_1d)
print(arr_2d)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


#List vs Numpy Array

In [9]:
py_list=[1,2,3]
print("Python list:",py_list * 2)

ny_array=np.array([1,2,3])
print("Numpy array:",ny_array * 2)

import time

start=time.time()
py_list=[i*2 for i in range(1000000)]
print("Time taken for python list:",time.time()-start)

start2=time.time()
ny_array=np.arange(1000000)*2
print("Time taken for numpy array:",time.time()-start2)

Python list: [1, 2, 3, 1, 2, 3]
Numpy array: [2 4 6]
Time taken for python list: 0.10519576072692871
Time taken for numpy array: 0.006287813186645508


#Creating array from scratch

In [10]:
zero=np.zeros((3,4))
print("Zeros:\n",zero)

ones=np.ones((3,3))
print("Ones:\n",ones)

full=np.full((3,3),20)
print("Use of FULL array:\n",full)

random=np.random.random((2,3))
print("Random array:\n",random)

sequence=np.arange(0,20,2)
print("Sequence array:\n",sequence)

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Use of FULL array:
 [[20 20 20]
 [20 20 20]
 [20 20 20]]
Random array:
 [[0.43535065 0.07933896 0.21371273]
 [0.47379784 0.08104531 0.13420763]]
Sequence array:
 [ 0  2  4  6  8 10 12 14 16 18]


### Vector , Matrix and Tensor

In [13]:
vector=np.array([1,2,3])
print("Vector:",vector)

matrix=np.array([[2,3,4],[4,5,6]])
print("Matrix:",matrix)

tensor=np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])
print("Tensor:\n",tensor)

Vector: [1 2 3]
Matrix: [[2 3 4]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


###Array Properties

In [15]:
arr=np.array([[10,20,30],
              [50,60,"70.5"]])

print("Shape of the array:",arr.shape)
print("Dimension of the array:",arr.ndim)
print("Size of the array:",arr.size)
print("Data Type of the array:",arr.dtype)

Shape of the array: (2, 3)
Dimension of the array: 2
Size of the array: 6
Data Type of the array: <U21


###ARRAY Reshaping

In [21]:
arr=np.arange(12)
print("Simple Array:\n",arr)

reshape=arr.reshape((4,3))
print("Reshaped Array:\n",reshape)

flattend=reshape.flatten()
print("Flattend Array:\n",flattend)

# ravel(returns view,instead of copy)
#that means the original does not get changed
raveled=reshape.ravel()
print("Raveled Array:\n",raveled)

transpose=reshape.T
print("Transposed Array:\n",transpose)

Simple Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Flattend Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array:
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
