In [2]:
import numpy as np

#Creating array from list

In [3]:
arr_1d=np.array([1,2,3,4,5,6])
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_1d)
print(arr_2d)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


#List vs Numpy Array