###Numpy Array Operations

In [1]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
#arr=np.arange(1,11)
print("Basic slicing:",arr[2:9])
print("With step:",arr[1:6:2])
print("Negative Slicing:",arr[-5])

Basic slicing: [3 4 5 6 7 8 9]
With step: [2 4 6]
Negative Slicing: 6


### Operations on 2D array

In [9]:
                # 0 1 2   
arr_2d=np.array([[1,2,3],  #0
                 [4,5,6],  #1
                 [7,8,9]]) #2

print("Single Element:",arr_2d[0,1])
# print("Single Element:",arr_2d[row,column])
print("Entire row:",arr_2d[2])
print("Entire column:",arr_2d[:,1])

Single Element: 2
Entire row: [7 8 9]
Entire column: [2 5 8]


### Sorting

In [16]:
unsorted=np.array([2,3,21,4,3,3,1])
print("Sorting 1D array:",np.sort(unsorted))

unsorted_2d=np.array([[8,1,3,4],
                      [6,1,3,1],
                      [1,4,2,9]])
print("Sorting 2D array by column:\n",np.sort(unsorted_2d,axis=0))
print("Sorting 2D array by row:\n",np.sort(unsorted_2d,axis=1))

Sorting 1D array: [ 1  2  3  3  3  4 21]
Sorting 2D array by column:
 [[1 1 2 1]
 [6 1 3 4]
 [8 4 3 9]]
Sorting 2D array by row:
 [[1 3 4 8]
 [1 1 3 6]
 [1 2 4 9]]


### Filtering

In [ ]:
numbers=np.array([1,2,34,2,2,5,14,13])
even_numbers=numbers[numbers%2==0]
print("Even Numbers:",even_numbers)

[ 2 34  2  2 14]


### Filtering with Mask

In [18]:
mask=numbers>15
print("Numbers greater than 15:",numbers[mask])

Numbers greater than 15: [34]


### Fancy Indexing v/s np.where()